# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SWORK' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'Alamofire', '~> 5.2'

  # Pods for SWORK

  target 'SWORKTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SWORKUITests' do
    # Pods for testing
  end

end
